# Task 3: Research Results, Data Analysis, and Scientific Visualization
**Project:** Fast Dopamine & Academic Performance — GPA Prediction Benchmark  
**Repository:** `https://github.com/EraMiir/fast-dopamine-academic-performance`

This notebook executes the complete reproducible analysis pipeline:
1. **Data Ingestion & Warm-up Filtering:** Loading raw benchmark logs (`data/raw/test_run.jsonl`) and discarding cold-start `warmup` runs.
2. **Statistical Aggregation:** Computing Mean, SD, Median, Percentiles ($p_{25}, p_{75}, p_{95}, p_{99}$), Bootstrapped 95% Confidence Intervals (CI), and Guardrail Error Rates.
3. **Scientific Visualization & Export:** Generating colorblind-safe plots with explicit physical units, log scales, and 95% CI bands exported to `.pdf` and 300 DPI `.png`.

In [1]:
# 1. Load Processed Summary & Verify Metrics
import pandas as pd
import numpy as np
df_summary = pd.read_csv("../data/processed/metrics_summary.csv")
print("Доступные колонки в сводке:", list(df_summary.columns))
display(df_summary[["model", "sample_size", "RMSE_median", "RMSE_ci_low", "RMSE_ci_high", "wilcoxon_p_value"]])

Доступные колонки в сводке: ['model', 'sample_size', 'n_runs', 'RMSE_median', 'RMSE_mean', 'RMSE_std', 'RMSE_p25', 'RMSE_p75', 'RMSE_p95', 'RMSE_iqr', 'RMSE_ci_low', 'RMSE_ci_high', 'baseline_RMSE_median', 'RMSE_diff_mean', 'RMSE_diff_ci_low', 'RMSE_diff_ci_high', 'wilcoxon_p_value', 'significant_vs_baseline', 'latency_ms_median', 'latency_ms_p25', 'latency_ms_p75', 'latency_ms_p95', 'latency_ms_ci_low', 'latency_ms_ci_high', 'ram_mb_median', 'ram_mb_p95', 'ram_mb_ci_low', 'ram_mb_ci_high', 'error_rate']

,model,sample_size,RMSE_median,RMSE_ci_low,RMSE_ci_high,wilcoxon_p_value
0,Ridge,64,0.2015,0.1785,0.2307,0.000001
1,Random Forest,64,0.2678,0.2500,0.2843,0.000001
2,Gradient Boosting,64,0.2688,0.2503,0.3054,0.000001
3,Ridge,128,0.1853,0.1639,0.1987,0.000001
4,Random Forest,128,0.2318,0.2204,0.2511,0.000001
5,Gradient Boosting,128,0.2319,0.2143,0.2536,0.000001
6,Ridge,192,0.2005,0.1930,0.2130,0.000001
7,Random Forest,192,0.2471,0.2361,0.2595,0.000001
8,Gradient Boosting,192,0.2492,0.2370,0.2546,0.000001
9,Ridge,256,0.1939,0.1842,0.2032,0.000001
10,Random Forest,256,0.2262,0.2202,0.2391,0.000001
11,Gradient Boosting,256,0.2304,0.2249,0.2424,0.000001

In [2]:
# 1. Load Processed Summary & Verify Metrics
import pandas as pd
import numpy as np
df_summary = pd.read_csv("../data/processed/metrics_summary.csv")
print("Доступные колонки в сводке:", list(df_summary.columns))
display(df_summary[["model", "sample_size", "RMSE_median", "RMSE_ci_low", "RMSE_ci_high", "wilcoxon_p_value"]])

Доступные колонки в сводке: ['model', 'sample_size', 'n_runs', 'RMSE_median', 'RMSE_mean', 'RMSE_std', 'RMSE_p25', 'RMSE_p75', 'RMSE_p95', 'RMSE_iqr', 'RMSE_ci_low', 'RMSE_ci_high', 'baseline_RMSE_median', 'RMSE_diff_mean', 'RMSE_diff_ci_low', 'RMSE_diff_ci_high', 'wilcoxon_p_value', 'significant_vs_baseline', 'latency_ms_median', 'latency_ms_p25', 'latency_ms_p75', 'latency_ms_p95', 'latency_ms_ci_low', 'latency_ms_ci_high', 'ram_mb_median', 'ram_mb_p95', 'ram_mb_ci_low', 'ram_mb_ci_high', 'error_rate']

,model,sample_size,RMSE_median,RMSE_ci_low,RMSE_ci_high,wilcoxon_p_value
0,Ridge,64,0.2015,0.1785,0.2307,0.000001
1,Random Forest,64,0.2678,0.2500,0.2843,0.000001
2,Gradient Boosting,64,0.2688,0.2503,0.3054,0.000001
3,Ridge,128,0.1853,0.1639,0.1987,0.000001
4,Random Forest,128,0.2318,0.2204,0.2511,0.000001
5,Gradient Boosting,128,0.2319,0.2143,0.2536,0.000001
6,Ridge,192,0.2005,0.1930,0.2130,0.000001
7,Random Forest,192,0.2471,0.2361,0.2595,0.000001
8,Gradient Boosting,192,0.2492,0.2370,0.2546,0.000001
9,Ridge,256,0.1939,0.1842,0.2032,0.000001
10,Random Forest,256,0.2262,0.2202,0.2391,0.000001
11,Gradient Boosting,256,0.2304,0.2249,0.2424,0.000001

In [3]:
# 3. Scientific Visualizations Generation
import sys
sys.path.append("../src")
import visualize
visualize.generate_plots("../configs/config.yaml")
print("[OK] Все графики успешно сгенерированы из ноутбука!")

[OK] Сохранены графики: /workspaces/fast-dopamine-academic-performance/results/figures/rmse_vs_sample_size.pdf и /workspaces/fast-dopamine-academic-performance/results/figures/rmse_vs_sample_size.png (300 DPI)

[OK] Сохранены графики: /workspaces/fast-dopamine-academic-performance/results/figures/latency_vs_sample_size.pdf и /workspaces/fast-dopamine-academic-performance/results/figures/latency_vs_sample_size.png (300 DPI)

[OK] Сохранены графики: /workspaces/fast-dopamine-academic-performance/results/figures/paired_rmse_difference.pdf и /workspaces/fast-dopamine-academic-performance/results/figures/paired_rmse_difference.png (300 DPI)
[OK] Все графики успешно сгенерированы из ноутбука!